---
title: "Genre Breakdown"
author: "Study Group 8"
date: "`r Sys.Date()`"
output: 
    html_document:
      number_sections: true
      highlight: zenburn
      theme: flatly
      toc: yes
      toc_depth: 2
      toc_float:
        collapsed: false
      fontsize: 10pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(vroom)
library(janitor)
library(skimr)
library(vroom)
library(mice) 
library(VIM)

```

# Exploring Covid data

## Data

```{r, get_data}
Twitch_game_data <- read_csv(here::here("Group Assignment","Twitch_Game_Merged.csv")) %>% 
  janitor::clean_names() 

```


```{r Genre Analysis}

# Select the top 10 genres by total hours watched
top_10_genres <- Twitch_game_data %>%
  group_by(genre) %>%
  summarise(Total_hours_watched = sum(hours_watched)) %>%
  arrange(desc(Total_hours_watched)) %>%
  filter(genre != "Shooter") %>%
  top_n(5)

# Filter Twitch_genre_perf to include only the top 10 genres
top_10_data <- Twitch_game_data %>%
  filter(genre %in% top_10_genres$genre) %>% 
  group_by(genre, year) %>% 
  summarise(Total_hours_watched = sum(hours_watched))


Top10_genres_watched <- ggplot(top_10_data, aes(x = year, y = Total_hours_watched, fill = genre)) +
  geom_area() +
  labs(title = "Evolution of Top 10 Genres",
       x = "Year",
       y = "Total Hours Watched") +
  theme_bw() +
  theme(panel.grid = element_blank(),  # Remove all gridlines
        legend.position = c(0.01, 0.99),  # Top left corner
        legend.justification = c(0.01, 0.99),  # Top left corner
        legend.box.margin = margin(0, 0, 0, 0),  # Reduce margin around legend
        legend.margin = margin(0, 0, 0, 0))  # Reduce margin around legend

# Save the plot as a PNG file
ggsave("Top10_genres_watched_stacked_area.png", plot = Top10_genres_watched, width = 10, height = 6, units = "in")





```

```{r Share of Genre Analysis}
# Select the top 10 genres by total hours watched
top_10_genres <- Twitch_game_data %>%
  group_by(genre) %>%
  summarise(Total_hours_watched = sum(hours_watched)) %>%
  arrange(desc(Total_hours_watched)) %>%
  top_n(10)

# Filter Twitch_genre_perf to include only the top 10 genres
top_10_data <- Twitch_game_data %>%
  filter(genre %in% top_10_genres$genre) %>% 
  group_by(genre, year) %>% 
  summarise(Total_hours_watched = sum(hours_watched))

# Create a new column to identify if the genre is in the top 10 or not
Twitch_game_data <- Twitch_game_data %>%
  mutate(is_top_10 = ifelse(genre %in% top_10_genres$genre, "Top 10", "Others"))

total_hours_by_group <- Twitch_game_data %>%
  group_by(year, is_top_10) %>%
  summarise(Total_hours_watched = sum(hours_watched)) %>% 
  mutate(Percentage = (Total_hours_watched / sum(Total_hours_watched)) * 100)

# Plotting the stacked bar chart
Proportion_top10 <- ggplot(total_hours_by_group, aes(x = year, y = Total_hours_watched, fill = is_top_10)) +
  geom_bar(stat = "identity") + 
  labs(title = "Proportion of Watching Hours Over Time",
       x = "Year",
       y = "Total Hours Watched",
       fill = "Genre Group") +
  scale_fill_manual(values = c("Top 10" = "red", "Others" = "gray")) +  # Set colors for the groups
  theme_bw() +  # Add the missing '+'
  theme(legend.position = c(0.01, 0.99),  # Top left corner
        legend.justification = c(0.01, 0.99),  # Top left corner
        legend.box.margin = margin(0, 0, 0, 0),  # Reduce margin around legend
        legend.margin = margin(0, 0, 0, 0)) +  # Reduce margin around legend
  geom_text(aes(label = sprintf("%.1f%%", Percentage)),
            position = position_stack(vjust = 0.5), 
            color = "white", 
            size = 3) +  # Add percentage labels 
   theme(panel.grid = element_blank()) 

ggsave("Proportion_top10.png", plot = Proportion_top10, width = 10, height = 6, units = "in")





```





